export const categories = [
  ["Chiave inglese", "Cacciavite", "Martello", "Pinze", "Trapano"],
  ["Adorabile", "Affascinante", "Incantevole", "Carino", "Amabile"],
  ["Cucinare", "Infornare", "Grigliare", "Saltare", "Arrostire"],
  ["Tigre", "Leone", "Giaguaro", "Leopardo", "Ghepardo"],
  ["Imprevedibile", "Eccentrico", "Volatile", "Capriccioso", "Incoerente"],
  ["Pianoforte", "Violino", "Violoncello", "Chitarra", "Arpa"],
  ["Navigare", "Dirigere", "Guidare", "Sterzare", "Pilotare"],
  ["Desolato", "Arido", "Vuoto", "Solitudine", "Abbandonato"],
  ["Medico", "Infermiera", "Chirurgo", "Paramedico", "Dottore"],
  ["Luminoso", "Splendente", "Luce intensa", "Radiante", "Brillante"],
  ["Tablet", "Portatile", "Smartphone", "Computer", "E-reader"],
  ["Eseguire", "Recitare", "Realizzare", "Consegnare", "Presentare"],
  ["Ardente", "Appassionato", "Fervente", "Zelante"],
  ["Architetto", "Costruttore", "Ingegnere", "Disegnatore", "Progettista"],
  ["Turbulento", "Tempestoso", "Agitato", "Mosso", "Instabile"],
  ["Discutere", "Conversare", "Litigare", "Deliberare", "Negoziare"],
  ["Sereno", "Calmo", "Tranquillo", "Pacato", "Silenzioso"],
  ["Tastiera", "Mouse", "Monitor", "Stampante", "Scanner"],
  ["Infastidire", "Irritare", "Disturbare", "Seccare", "Agitare"],
  ["Brillante", "Genio", "Astuto", "Intelligente", "Sveglio"],
  ["Bicicletta", "Monopattino", "Skateboard", "Pattini", "Segway"],
  ["Resistere", "Sopportare", "Sopravvivere", "Persistere", "Superare"],
  ["Misterioso", "Enigmatico", "Criptico", "Misterioso", "Intrigante"],
  ["Giacca", "Cappotto", "Maglione", "Gilet", "Blazer"],
  ["Urlare", "Gridare", "Strillare", "Ruggire", "Ululare"],
  ["Antico", "Storico", "Vecchio", "Antiquato", "Senza tempo"],
  ["Escursionismo", "Campeggio", "Pesca", "Ciclismo", "Arrampicata"],
  ["Scolpire", "Intagliare", "Scalpello", "Modellare"],
  ["Caldo", "Accogliente", "Confortevole", "Riscaldato", "Comodo"],
  ["Prosperare", "Fiorire", "Aver successo", "Crescere"],
  ["Noioso", "Spuntato", "Stanco", "Piatto", "Poco interessante"],
  ["Quaderno", "Diario", "Taccuino", "Agenda", "Registro"],
  ["Energico", "Dinamico", "Vivace", "Attivo"],
  ["Giungla", "Foresta", "Foresta pluviale", "Bosco", "Macchia"],
  ["Elegante", "Lucido", "Raffinato", "Liscio"],
  ["Sistema", "Rete", "Struttura", "Organizzazione", "Modello"],
  ["Opulento", "Lussuoso", "Sontuoso", "Sfarzoso", "Ricco"],
  ["Conferenza", "Seminario", "Workshop", "Simposio", "Vertice"],
  ["Schizzare", "Disegnare", "Contornare", "Illustrare", "Progettare"],
  ["Curioso", "Inquisitivo", "Desideroso", "Interrogativo", "Interessato"],
  ["Tavolozza", "Tela", "Cavalletto", "Pennello", "Pigmento"],
  ["Accelerare", "Velocizzare", "Aumentare", "Affrettare", "Sollecitare"],
  ["Delicato", "Fragile", "Friabile", "Tenero", "Debole"],
  ["Calcolare", "Computare", "Misurare", "Stimare"],
  ["Cuscino", "Coperta", "Piumone", "Lenzuolo", "Duvet"],
  ["Ispirare", "Motivare", "Incoraggiare", "Stimolare", "Influenzare"],
  ["Tappeto", "Stuoia", "Zerbino", "Passatoia", "Arazzo"],
  ["Analizzare", "Esaminare", "Scrutinare", "Indagare", "Valutare"],
  ["Criminale", "Delinquente", "Sospetto", "Colpevole", "Fuorilegge"],
  ["Ostacolo", "Barriera", "Impedimento", "Sfida", "Difficoltà"],
  ["Museo", "Galleria", "Mostra", "Esposizione", "Collezione"]
];