import type { WordsMeaningData } from "@components/TestApp/types";

export default [
  ["Llave inglesa", "Destornillador", "Martillo", "Alicates", "Taladro"],
  ["Adorable", "Encantador", "Cautivador", "Lindo", "Enternecedor"],
  ["Cocinar", "Hornear", "Asar", "Saltear", "Rostizar"],
  ["Tigre", "León", "Jaguar", "Leopardo", "Guepardo"],
  ["Impredecible", "Errático", "Volátil", "Inconstante", "Inconsistente"],
  ["Piano", "Violín", "Violonchelo", "Guitarra", "Arpa"],
  ["Navegar", "Dirigir", "Guiar", "Conducir", "Pilotar"],
  ["Desolado", "Árido", "Vacío", "Solitario", "Abandonado"],
  ["Médico", "Enfermera", "Cirujano", "Paramédico", "Doctor"],
  ["Brillante", "Reluciente", "Luminoso", "Radiante", "Resplandeciente"],
  [
    "Tableta",
    "Portátil",
    "Teléfono inteligente",
    "Computadora",
    "Lector electrónico",
  ],
  ["Realizar", "Actuar", "Ejecutar", "Hacer", "Acabar"],
  ["Ardiente", "Apasionado", "Ferviente", "Entusiasta"],
  ["Arquitecto", "Constructor", "Ingeniera", "Dibujante", "Diseñadora"],
  ["Turbulento", "Tormentoso", "Tempestuoso", "Inestable", "Agitado"],
  ["Debatir", "Discutir", "Argumentar", "Deliberar", "Negociar"],
  ["Sereno", "Tranquilo", "Pacífico", "Calmado", "Sosegado"],
  ["Teclado", "Ratón", "Monitor", "Impresora", "Escáner"],
  ["Molestar", "Irritar", "Perturbar", "Incomodar", "Agitar"],
  ["Brillante", "Genio", "Inteligente", "Listo", "Astuto"],
  ["Bicicleta", "Patinete", "Monopatín", "Patines", "Segway"],
  ["Soportar", "Resistir", "Superar", "Tolerar", "Aguantar"],
  ["Misterioso", "Enigmático", "Críptico", "Desconcertante", "Intrigante"],
  ["Chaqueta", "Abrigo", "Suéter", "Chaleco", "Jersey"],
  ["Gritar", "Chillar", "Vociferar", "Rugir", "Aullar"],
  ["Antiguo", "Histórico", "Viejo", "Anticuado", "Ancestral"],
  ["Senderismo", "Camping", "Pesca", "Ciclismo", "Escalada"],
  ["Esculpir", "Tallar", "Cincelar", "Moldear"],
  ["Cálido", "Acogedor", "Cómodo", "Hospitalario", "Abrigado"],
  ["Prosperar", "Florecer", "Progresar", "Crecer"],
  ["Aburrido", "Desganado", "Hastiado", "Tedioso", "Insulso"],
  ["Cuaderno", "Diario", "Bloc", "Agenda", "Bitácora"],
  ["Enérgico", "Dinámico", "Vivaz", "Activo"],
  ["Jungla", "Bosque", "Selva", "Arboleda", "Matorral"],
  ["Elegante", "Distinguido", "Refinado", "Exquisito"],
  ["Sistema", "Red", "Estructura", "Marco", "Modelo"],
  ["Opulento", "Lujoso", "Suntuoso", "Fastuoso", "Rico"],
  ["Conferencia", "Seminario", "Taller", "Simposio", "Cumbre"],
  ["Bocetar", "Dibujar", "Esbozar", "Ilustrar", "Diseñar"],
  ["Curioso", "Indiscreto", "Fisgón", "Preguntón", "Intruso"],
  ["Paleta", "Lienzo", "Caballete", "Pincel", "Pigmento"],
  ["Acelerar", "Velocidad", "Impulsar", "Apremiar", "Rápido"],
] satisfies WordsMeaningData;
