export const categories = [
  ["Clé", "Tournevis", "Marteau", "Pince", "Perceuse"], // Tous les mots sont des outils utilisés pour le travail mécanique (noms)
  ["Adorable", "Charmant", "Joli", "Mignon", "Attendrissant"], // Tous les mots décrivent des qualités agréables ou attirantes (adjectifs)
  ["Cuisiner", "Cuire", "Griller", "Sauter", "Rôtir"], // Tous les mots décrivent des méthodes de préparation des aliments (verbes)
  ["Tigre", "Lion", "Jaguar", "Léopard", "Guépard"], // Tous les mots sont des grands félins (noms)
  ["Imprévisible", "Erratique", "Volatile", "Changeant", "Inconstant"], // Tous les mots décrivent un manque de prévisibilité (adjectifs)
  ["Piano", "Violon", "Violoncelle", "Guitare", "Harpe"], // Tous les mots sont des instruments à cordes (noms)
  ["Naviguer", "Diriger", "Guider", "Manœuvrer", "Piloter"], // Tous les mots concernent le contrôle du mouvement (verbes)
  ["Désolé", "Stérile", "Vide", "Solitaire", "Abandonné"], // Tous les mots décrivent un manque d'habitants ou d'activité (adjectifs)
  ["Médecin", "Infirmier", "Chirurgien", "Paramédic", "Docteur"], // Tous les mots sont des professionnels médicaux (noms)
  ["Brillant", "Lumineux", "Radieux", "Resplendissant", "Éclatant"], // Tous les mots décrivent une forte lumière ou brillance (adjectifs)
  ["Tablette", "Ordinateur portable", "Smartphone", "Ordinateur", "Liseuse"], // Tous les mots sont des appareils électroniques (noms)
  ["Exécuter", "Agir", "Réaliser", "Présenter", "Jouer"], // Tous les mots concernent l'accomplissement d'actions ou de tâches (verbes)
  ["Ardent", "Passionné", "Fervent", "Zélé"], // Tous les mots décrivent de forts sentiments ou enthousiasme (adjectifs)
  ["Architecte", "Constructeur", "Ingénieur", "Dessinateur", "Designer"], // Tous les mots sont des professionnels de la construction ou du design (noms)
  ["Turbulent", "Orageux", "Agité", "Instable", "Secoué"], // Tous les mots décrivent des conditions instables (adjectifs)
  ["Débattre", "Discuter", "Argumenter", "Délibérer", "Négocier"], // Tous les mots impliquent un échange d'idées (verbes)
  ["Serein", "Calme", "Tranquille", "Paisible", "Silencieux"], // Tous les mots décrivent un état de calme (adjectifs)
  ["Clavier", "Souris", "Écran", "Imprimante", "Scanner"], // Tous les mots sont des périphériques informatiques (noms)
  ["Agacer", "Irriter", "Déranger", "Gêner", "Exciter"], // Tous les mots décrivent le fait de causer de l'inconfort (verbes)
  ["Brillant", "Génie", "Intelligent", "Malin", "Astucieux"], // Tous les mots décrivent un haut niveau d'intellect (adjectifs)
  ["Vélo", "Trottinette", "Skateboard", "Rollers", "Segway"], // Tous les mots sont des moyens de transport personnel (noms)
  ["Endurer", "Résister", "Survivre", "Persister", "Surmonter"], // Tous les mots concernent le fait de surmonter des défis (verbes)
  ["Mystérieux", "Énigmatique", "Cryptique", "Déroutant", "Intrigant"], // Tous les mots décrivent quelque chose de difficile à comprendre (adjectifs)
  ["Veste", "Manteau", "Pull", "Gilet", "Blazer"], // Tous les mots sont des vêtements d'extérieur (noms)
  ["Crier", "Hurler", "Vociférer", "Rugir", "Gémir"], // Tous les mots décrivent des expressions vocales fortes (verbes)
  ["Ancien", "Historique", "Vieux", "Antique", "Intemporel"], // Tous les mots décrivent quelque chose avec une longue histoire (adjectifs)
  ["Randonnée", "Camping", "Pêche", "Vélo", "Escalade"], // Tous les mots sont des activités de plein air (noms)
  ["Sculpter", "Tailler", "Ciseler", "Façonner"], // Tous les mots concernent la création de formes (verbes)
  ["Chaud", "Douillet", "Confortable", "Chauffé", "Moelleux"], // Tous les mots décrivent une chaleur agréable (adjectifs)
  ["Prospérer", "Fleurir", "Grandir", "Évoluer"], // Tous les mots concernent le développement réussi (verbes)
  ["Terne", "Émoussé", "Fatigué", "Plat", "Inintéressant"], // Tous les mots décrivent un manque d'intérêt ou de netteté (adjectifs)
  ["Carnet", "Journal", "Bloc-notes", "Agenda", "Journal intime"], // Tous les mots sont des supports d'écriture (noms)
  ["Énergique", "Dynamique", "Vif", "Actif"], // Tous les mots décrivent un haut niveau d'énergie (adjectifs)
  ["Jungle", "Forêt", "Rainforest", "Bois", "Fourré"], // Tous les mots sont des environnements boisés denses (noms)
  ["Lisse", "Poli", "Élégant", "Doux"], // Tous les mots décrivent une apparence raffinée (adjectifs)
  ["Système", "Réseau", "Cadre", "Structure", "Modèle"], // Tous les mots décrivent des ensembles organisés (noms)
  ["Opulent", "Luxueux", "Somptueux", "Extravagant", "Riche"], // Tous les mots décrivent le luxe ou la richesse (adjectifs)
  ["Conférence", "Séminaire", "Atelier", "Symposium", "Sommet"], // Tous les mots sont des rassemblements professionnels (noms)
  ["Esquisser", "Dessiner", "Tracer", "Illustrer", "Designer"], // Tous les mots concernent la création de représentations visuelles (verbes)
  ["Curieux", "Enquêteur", "Avide", "Questionneur", "Intéressé"], // Tous les mots décrivent le désir de connaissance (adjectifs)
  ["Palette", "Toile", "Chevalet", "Pinceau", "Pigment"], // Tous les mots sont des outils ou matériaux de peinture (noms)
  ["Accélérer", "Vitesse", "Booster", "Hâter", "Rapide"], // Tous les mots concernent l'augmentation de la vitesse (verbes)
  ["Délicat", "Fragile", "Cassant", "Tendre", "Frêle"], // Tous les mots décrivent quelque chose de facilement cassable (adjectifs)
  ["Calculer", "Compter", "Mesurer", "Estimer"], // Tous les mots concernent la détermination de quantités (verbes)
  ["Oreiller", "Couverture", "Édredon", "Drap", "Duvet"], // Tous les mots sont des articles de literie (noms)
  ["Inspirer", "Motiver", "Encourager", "Stimuler", "Influencer"], // Tous les mots concernent la stimulation d'une action ou émotion (verbes)
  ["Tapis", "Moquette", "Paillasson", "Chemin de table", "Tapisserie"], // Tous les mots sont des revêtements de sol (noms)
  ["Analyser", "Examiner", "Scruter", "Enquêter", "Évaluer"], // Tous les mots concernent l'étude approfondie (verbes)
  ["Criminel", "Délinquant", "Suspect", "Auteur", "Hors-la-loi"], // Tous les mots décrivent des personnes impliquées dans des activités illégales (noms)
  ["Obstacle", "Barrière", "Entrave", "Défi", "Impediment"], // Tous les mots décrivent ce qui entrave le progrès (noms)
  ["Musée", "Galerie", "Exposition", "Vitrine", "Collection"], // Tous les mots sont liés à des lieux ou événements d'art (noms)
];
